name: Deploy - EsportsCompare

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: EsportsCompare
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Change  for environment
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "{{ ESPORTSCOMPARE_ISSUER }}"
          replace: ${{ env.ESPORTSCOMPARE_ISSUER }}
          include: "**appsettings.json"
      
      - name: Change  for environment
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "{{ ESPORTSCOMPARE_AUDIENCE }}"
          replace: ${{ env.ESPORTSCOMPARE_AUDIENCE }}
          include: "**appsettings.json"

      - name: Change 2 for environment
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "{{ KEY }}"
          replace: ${{ env.KEY }}
          include: "**appsettings.json"

      - name: Change  for environment
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "{{ DefaultConnection }}"
          replace: ${{ env.DefaultConnection }}
          include: "**appsettings.json"

      - name: Change  for environment
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "{{ ESPORTSCOMPARE_FRONTEND_URL }}"
          replace: ${{ env.ESPORTSCOMPARE_FRONTEND_URL }}
          include: "**appsettings.json"

      - name: Restore
        run: dotnet restore src/EsportsProfileApi.Web/EsportsProfileWebApi.Web.sln
      
      - name: Build with dotnet
        run: dotnet build src/EsportsProfileApi.Web/EsportsProfileWebApi.Web.sln --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish src/EsportsProfileApi.Web/EsportsProfileWebApi.Web.sln --configuration Release --no-build --output ${{ env.DOTNET_ROOT }}/EsportsCompare

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: ${{ env.DOTNET_ROOT }}/EsportsCompare

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
      
      - name: Login to Azure
        uses: azure/login@v1.4.7
        with:
          creds : ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .