# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SETSRV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_8d4de6e776ee41a6a21fa6cf5ea9295b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_911cacc55e164734a7e620e4d347e921 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_8d4de6e776ee41a6a21fa6cf5ea9295b }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SETSRV'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5bd84409041a45828322b0a67fd5c2bd }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_8d4de6e776ee41a6a21fa6cf5ea9295b }}/appsvc/staticsite:${{ github.sha }}'